### ISSUE TITLE
IndexError: list index out of range in Adafruit_IO/errors.py, line 66, in __init__

### ISSUE THREAD

**Issue by amosistech** [adafruit/Adafruit_IO_Python#142] opened 2022-05-04 05:05 UTC
Hi all,

I am facing a problem with Adafruit_IO package, I am subscribed to a feed and eventually my program crashed with the following error:

File "/home/pi/Documents/Python/warbots/venv/lib/python3.9/site-packages/Adafruit_IO/errors.py", line 66, in __init__
    error = MQTT_ERRORS[response]
IndexError: list index out of range

To managed this error I change Adafruit_IO/errors.py adding the last two lines to MQTT_ERRORS  constant :

MQTT_ERRORS   = [ 'Connection successful',
                  'Incorrect protocol version',
                  'Invalid Client ID',
                  'Server unavailable ',
                  'Bad username or password',
                  'Not authorized',
                  '6 - Unknown',
                  '7 - Unknown' ]

After patching client.py it helps to avoid crashes, however after two or four days my program is disconected from the feed (previously it remains connected forever, I suspect the problem start showing after I change python version) and  my program is disconnected with MQTT_ERROR 7.

The interesting think is that the on_disconnect callback function is never executed.

In order to diagnose the problem I turn on the loggin option in Adafruit_IO and pago.mqtt and I collect the following errors:

2022-05-01 00:51:34,828 DEBUG:     Adafruit_IO.mqtt_client / mqtt_client / _mqtt_disconnect / Client on_disconnect called.
2022-05-01 00:51:34,828 ERROR:     paho.mqtt.client / client / _easy_log / Caught exception in on_disconnect: 7 - Unknown

Also I noted that paho have a lot more mqtt error that must managed in Adafruit_IO and not only error 6 or 7.

In summary, after patching Adafruit_IO I discover the problem comes from paqo.mqtt and showing an unknown error 7, that for the moment I can not found what is the meaning of this error cod in paho-mqtt

This is my info:

- Platform/operating system 
Raspberry PI (bullseye)

- Python version (run `python -version` or `python3 -version`):  
Python 3.9.2

adafruit_io==2.6.0
paho-mqtt==1.6.1

- Error message you are receiving, including any Python exception traces:  
2022-05-01 00:51:34,828 DEBUG:     Adafruit_IO.mqtt_client / mqtt_client / _mqtt_disconnect / Client on_disconnect called.
2022-05-01 00:51:34,828 ERROR:     paho.mqtt.client / client / _easy_log / Caught exception in on_disconnect: 7 - Unknown

- List the steps to reproduce the problem below (if possible attach code or commands
  to run): 
Connect to Adafruit_IO and set the callback functions, after few days the program lost connection (see reasons above) 

Best Regards

Douglas

**Comment by RMcGhee** [comment] 2023-03-25 03:33
Did you ever come up with a resolution for this? Yours is the only explanation that matches my issue, but I can't seem to find any recent activity that deals with this. Thanks in advance.

**Comment by brentru** [comment] 2023-11-08 23:17
@amosistech @RMcGhee  I am not certain how this is going out of range. There are only 6 return codes in the CONNECT packet[1]. The array within `errors.py` looks like it is identical to those codes [1].

If you are able to provide instructions to reproduce this issue, please let me know. Otherwise, I am closing this issue.

[1] https://docs.emqx.com/en/cloud/latest/connect_to_deployments/mqtt_client_error_codes.html#connack-packet

**Closed by brentru** 2023-11-08 23:17 UTC
